//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace intermediary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addhouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Addhouse()
        {
            this.tenancy = new HashSet<tenancy>();
        }
    
        public int ID { get; set; }
        public Nullable<int> size { get; set; }
        public Nullable<int> monthly { get; set; }
        public string house { get; set; }
        public string style { get; set; }
        public string trimstate { get; set; }
        public string address { get; set; }
        public string purpose { get; set; }
        public string housestate { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tenancy> tenancy { get; set; }
    }
}
